### ISSUE TITLE
Feedback homework week 3

### ISSUE THREAD

**Issue by remarcmij** [kawaraa/hyf-js1#1]
Hi Ahmad, here is my feedback on your JS1 week 3 homework.

Your code looks well formatted, with code blocks nicely separated with a blank line and with semicolons in all the right places.

## Step 4: Strings and Array challenges

1. Excellent that you used the `.replace()` method in combination with a regular expression. We won't cover regular expressions in the lectures as it is an advanced, vast topic but at least you got a taste of it here.

    Note that you introduced a variable `arr` here which might suggest that it represents an array. However, its value is actually a string. So perhaps `str` or something like that might be a better name. Make sure that the variable names you choose always reflect their content.

2. Excellent! Note that there is a spelling error in `meerInedx`. It should be `meerIndex`. This spelling error was flagged in my VSCode by a wavy underline. There is also a wavy underline for `meerkat`, but of course that is not a spelling error, just a word that the spell checker does not have in its vocabulary.

## More JavaScript

1. While I think you grasped the concept of a function taking arguments and returning a value, the result is not the asked for sum of the arguments, but something else. I couldn't blindly take your function and trust it to produce the sum of its three arguments.

2. Correct.

3. While you can print out an object like you did, you are limited to the standard format that JavaScript uses for printing the contents of an object. What if I asked you to use an `=` sign instead of a `:` character to separate name and value and also want to get rid of `{` and `}`? You probably would need some kind of `for` loop.

4. Correct.

5. Correct.

6. Although your function looks correct, it is not executed. This is because you created a function with the same name in step 9, which overwrites the version of step 6. So, in line 60 you are actually calling the function of step 9, which produces the output `a Blue Motorbike` rather than `a Blue used car`. You can avoid this issue by renaming the function of step 9 to, say, `vehicle2`. Or you can put each exercise in a block scope as I have done in my solution of the homework.

7. Correct.

8. Correct.

9. Your function should use the `code` parameter to determine the type of vehicle to print out. In your version you have assumed that it is always a `bike`.

10. Your advertisement misses the expected commas between the vehicle types.

11. I had to look for it, as it precedes step 10.

12. Correct.

13. (14) See my solution for a more structured object.

15. (16, 17) You could add an explanation as a comment of what is happening here.

**Comment by kawaraa** [comment]
Corrects all the steps as required

**Comment by remarcmij** [comment]
For Step 9, this is my solution:

```js
```

**Comment by kawaraa** [comment]
beautiful and very professional! thank you!
